version: "3"
services:
  db:
    build:
      context: .
      dockerfile: postgres/Dockerfile
    container_name: "bar-postgres"
    ports:
      - "5432:5432"
    volumes:
      - bar_dbdata:/var/lib/postgresql/data
      - ./postgres/scripts:/scripts

volumes:
  bar_dbdata:
